"""Refresh the local IP threat-intel blocklist from free, no-key feeds.

Downloads the abuse.ch Feodo Tracker botnet C2 blocklist (public, free, no API
key) into data/threat_intel/ip_blocklist.txt, where aisoc.enrichment.context
reads it. Run this on a schedule (e.g. daily); the enrichment layer treats a
missing/empty file as a no-op, so nothing breaks if it hasn't been run.

    python scripts/update_threat_intel.py

Add more free feeds by extending FEEDS. Keep it to sources that need no key.
"""

from pathlib import Path

import httpx

OUT_PATH = Path("data/threat_intel/ip_blocklist.txt")

# name -> URL. All free, no API key required.
FEEDS = {
    "abuse.ch Feodo Tracker": "https://feodotracker.abuse.ch/downloads/ipblocklist.txt",
}


def main() -> None:
    ips: set[str] = set()
    for name, url in FEEDS.items():
        try:
            resp = httpx.get(url, timeout=30.0, follow_redirects=True)
            resp.raise_for_status()
        except httpx.HTTPError as exc:
            print(f"  WARNING: {name} fetch failed — {exc}")
            continue
        added = 0
        for line in resp.text.splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            ip = line.split(",")[0].strip()
            if ip and ip not in ips:
                ips.add(ip)
                added += 1
        print(f"  {name}: {added} IPs")

    if not ips:
        raise SystemExit("No IPs fetched — leaving existing blocklist untouched.")

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    header = "# aggregated free IP threat intel — regenerated by scripts/update_threat_intel.py\n"
    OUT_PATH.write_text(header + "\n".join(sorted(ips)) + "\n", encoding="utf-8")
    print(f"\nwrote {len(ips)} IPs -> {OUT_PATH}")


if __name__ == "__main__":
    main()
